Vagrant.configure("2") do |config|
  # Define base box
  config.vm.box = "generic/ubuntu2204"

  # Master Node
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.56.10"
    master.vm.provider :libvirt do |lv|
      lv.memory = 2048
      lv.cpus = 2
    end
  end

  # Worker Nodes
  (1..2).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.hostname = "worker#{i}"

      # Assign fixed IPs: 192.168.56.11 and 192.168.56.12
      ip = "192.168.56.#{10 + i}"  # => 11, 12
      worker.vm.network "private_network", ip: ip

      worker.vm.provider :libvirt do |lv|
        lv.memory = 1024
        lv.cpus = 1
      end
    end
  end
end
